#############################################################################
# Makefile for building: mahjong
# Generated by qmake (3.1) (Qt 6.8.1)
# Project:  project.pro
# Template: app
# Command: /Users/N/Qt/6.8.1/macos/bin/qmake -o Makefile project.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_OPENGL_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_QMLMETA_LIB -DQT_QMLMODELS_LIB -DQT_QMLWORKERSCRIPT_LIB -DQT_QML_LIB -DQT_QMLINTEGRATION_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=12 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=12 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I../../../N/Qt/6.8.1/macos/lib/QtQuick.framework/Headers -I../../../N/Qt/6.8.1/macos/lib/QtOpenGL.framework/Headers -I../../../N/Qt/6.8.1/macos/lib/QtMultimedia.framework/Headers -I../../../N/Qt/6.8.1/macos/lib/QtGui.framework/Headers -I../../../N/Qt/6.8.1/macos/lib/QtQmlMeta.framework/Headers -I../../../N/Qt/6.8.1/macos/lib/QtQmlModels.framework/Headers -I../../../N/Qt/6.8.1/macos/lib/QtQmlWorkerScript.framework/Headers -I../../../N/Qt/6.8.1/macos/lib/QtQml.framework/Headers -I../../../N/Qt/6.8.1/macos/include -I../../../N/Qt/6.8.1/macos/include/QtQmlIntegration -I../../../N/Qt/6.8.1/macos/lib/QtNetwork.framework/Headers -I../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../Qt/6.8.1/macos/mkspecs/macx-clang -F/Users/N/Qt/6.8.1/macos/lib
QMAKE         = /Users/N/Qt/6.8.1/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/N/Qt/6.8.1/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/N/Qt/6.8.1/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = mahjong1.0.0
DISTDIR = /Users/n/Desktop/Strategy-9/.tmp/mahjong1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/N/Qt/6.8.1/macos/lib
LIBS          = $(SUBLIBS) -F/Users/N/Qt/6.8.1/macos/lib -framework QtQuick -framework QtOpenGL -framework QtMultimedia -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtQmlMeta -framework QtQmlModels -framework QtQmlWorkerScript -framework QtQml -framework QtNetwork -framework QtCore -framework IOKit -framework DiskArbitration -framework UniformTypeIdentifiers -framework AGL -framework OpenGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp qrc_resources.cpp \
		moc_tile.cpp \
		moc_tilemodel.cpp \
		moc_board.cpp
OBJECTS       = main.o \
		qrc_resources.o \
		moc_tile.o \
		moc_tilemodel.o \
		moc_board.o
DIST          = src/qml/main.qml \
		../../Qt/6.8.1/macos/mkspecs/features/spec_pre.prf \
		../../Qt/6.8.1/macos/mkspecs/features/device_config.prf \
		../../Qt/6.8.1/macos/mkspecs/common/unix.conf \
		../../Qt/6.8.1/macos/mkspecs/common/mac.conf \
		../../Qt/6.8.1/macos/mkspecs/common/macx.conf \
		../../Qt/6.8.1/macos/mkspecs/common/sanitize.conf \
		../../Qt/6.8.1/macos/mkspecs/common/gcc-base.conf \
		../../Qt/6.8.1/macos/mkspecs/common/gcc-base-mac.conf \
		../../Qt/6.8.1/macos/mkspecs/common/clang.conf \
		../../Qt/6.8.1/macos/mkspecs/common/clang-mac.conf \
		../../Qt/6.8.1/macos/mkspecs/qconfig.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_ext_openxr_loader.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_core.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_help.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsplatform.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsplatform_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_network.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlmeta.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlnetwork.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3d.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dxr.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickvectorimage.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../../Qt/6.8.1/macos/mkspecs/features/qt_functions.prf \
		../../Qt/6.8.1/macos/mkspecs/features/qt_config.prf \
		../../Qt/6.8.1/macos/mkspecs/macx-clang/qmake.conf \
		../../Qt/6.8.1/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/6.8.1/macos/mkspecs/features/exclusive_builds.prf \
		../../Qt/6.8.1/macos/mkspecs/features/mac/sdk.prf \
		../../Qt/6.8.1/macos/mkspecs/features/toolchain.prf \
		../../Qt/6.8.1/macos/mkspecs/features/mac/toolchain.prf \
		../../Qt/6.8.1/macos/mkspecs/features/default_pre.prf \
		../../Qt/6.8.1/macos/mkspecs/features/mac/default_pre.prf \
		../../Qt/6.8.1/macos/mkspecs/features/resolve_config.prf \
		../../Qt/6.8.1/macos/mkspecs/features/default_post.prf \
		../../Qt/6.8.1/macos/mkspecs/features/mac/default_post.prf \
		../../Qt/6.8.1/macos/mkspecs/features/mac/objective_c.prf \
		../../Qt/6.8.1/macos/mkspecs/features/mac/mac.prf \
		../../Qt/6.8.1/macos/mkspecs/features/warn_on.prf \
		../../Qt/6.8.1/macos/mkspecs/features/permissions.prf \
		../../Qt/6.8.1/macos/mkspecs/features/qt.prf \
		../../Qt/6.8.1/macos/mkspecs/features/resources_functions.prf \
		../../Qt/6.8.1/macos/mkspecs/features/resources.prf \
		../../Qt/6.8.1/macos/mkspecs/features/moc.prf \
		../../Qt/6.8.1/macos/mkspecs/features/unix/opengl.prf \
		../../Qt/6.8.1/macos/mkspecs/features/unix/thread.prf \
		../../Qt/6.8.1/macos/mkspecs/features/qmake_use.prf \
		../../Qt/6.8.1/macos/mkspecs/features/file_copies.prf \
		../../Qt/6.8.1/macos/mkspecs/features/mac/rez.prf \
		../../Qt/6.8.1/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/6.8.1/macos/mkspecs/features/testcase_targets.prf \
		../../Qt/6.8.1/macos/mkspecs/features/exceptions.prf \
		../../Qt/6.8.1/macos/mkspecs/features/yacc.prf \
		../../Qt/6.8.1/macos/mkspecs/features/lex.prf \
		project.pro src/tile.hpp \
		src/tilemodel.hpp \
		src/board.hpp src/main.cpp
QMAKE_TARGET  = mahjong
DESTDIR       = 
TARGET        = mahjong

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 13.1
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/n/Desktop/Strategy-9/.qmake.stash
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = x86_64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/n/Desktop/Strategy-9/project.pro


include /Users/n/Qt/6.8.1/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

mahjong:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: project.pro ../../Qt/6.8.1/macos/mkspecs/macx-clang/qmake.conf ../../Qt/6.8.1/macos/mkspecs/features/spec_pre.prf \
		../../Qt/6.8.1/macos/mkspecs/features/device_config.prf \
		../../Qt/6.8.1/macos/mkspecs/common/unix.conf \
		../../Qt/6.8.1/macos/mkspecs/common/mac.conf \
		../../Qt/6.8.1/macos/mkspecs/common/macx.conf \
		../../Qt/6.8.1/macos/mkspecs/common/sanitize.conf \
		../../Qt/6.8.1/macos/mkspecs/common/gcc-base.conf \
		../../Qt/6.8.1/macos/mkspecs/common/gcc-base-mac.conf \
		../../Qt/6.8.1/macos/mkspecs/common/clang.conf \
		../../Qt/6.8.1/macos/mkspecs/common/clang-mac.conf \
		../../Qt/6.8.1/macos/mkspecs/qconfig.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_ext_openxr_loader.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_core.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_help.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsplatform.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsplatform_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_network.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlmeta.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlnetwork.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3d.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dxr.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickvectorimage.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../../Qt/6.8.1/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../../Qt/6.8.1/macos/mkspecs/features/qt_functions.prf \
		../../Qt/6.8.1/macos/mkspecs/features/qt_config.prf \
		../../Qt/6.8.1/macos/mkspecs/macx-clang/qmake.conf \
		../../Qt/6.8.1/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/6.8.1/macos/mkspecs/features/exclusive_builds.prf \
		../../Qt/6.8.1/macos/mkspecs/features/mac/sdk.prf \
		../../Qt/6.8.1/macos/mkspecs/features/toolchain.prf \
		../../Qt/6.8.1/macos/mkspecs/features/mac/toolchain.prf \
		../../Qt/6.8.1/macos/mkspecs/features/default_pre.prf \
		../../Qt/6.8.1/macos/mkspecs/features/mac/default_pre.prf \
		../../Qt/6.8.1/macos/mkspecs/features/resolve_config.prf \
		../../Qt/6.8.1/macos/mkspecs/features/default_post.prf \
		../../Qt/6.8.1/macos/mkspecs/features/mac/default_post.prf \
		../../Qt/6.8.1/macos/mkspecs/features/mac/objective_c.prf \
		../../Qt/6.8.1/macos/mkspecs/features/mac/mac.prf \
		../../Qt/6.8.1/macos/mkspecs/features/warn_on.prf \
		../../Qt/6.8.1/macos/mkspecs/features/permissions.prf \
		../../Qt/6.8.1/macos/mkspecs/features/qt.prf \
		../../Qt/6.8.1/macos/mkspecs/features/resources_functions.prf \
		../../Qt/6.8.1/macos/mkspecs/features/resources.prf \
		../../Qt/6.8.1/macos/mkspecs/features/moc.prf \
		../../Qt/6.8.1/macos/mkspecs/features/unix/opengl.prf \
		../../Qt/6.8.1/macos/mkspecs/features/unix/thread.prf \
		../../Qt/6.8.1/macos/mkspecs/features/qmake_use.prf \
		../../Qt/6.8.1/macos/mkspecs/features/file_copies.prf \
		../../Qt/6.8.1/macos/mkspecs/features/mac/rez.prf \
		../../Qt/6.8.1/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/6.8.1/macos/mkspecs/features/testcase_targets.prf \
		../../Qt/6.8.1/macos/mkspecs/features/exceptions.prf \
		../../Qt/6.8.1/macos/mkspecs/features/yacc.prf \
		../../Qt/6.8.1/macos/mkspecs/features/lex.prf \
		project.pro \
		src/resources/resources.qrc \
		../../../N/Qt/6.8.1/macos/lib/QtQuick.framework/Resources/QtQuick.prl \
		../../../N/Qt/6.8.1/macos/lib/QtOpenGL.framework/Resources/QtOpenGL.prl \
		../../../N/Qt/6.8.1/macos/lib/QtMultimedia.framework/Resources/QtMultimedia.prl \
		../../../N/Qt/6.8.1/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../../../N/Qt/6.8.1/macos/lib/QtQmlMeta.framework/Resources/QtQmlMeta.prl \
		../../../N/Qt/6.8.1/macos/lib/QtQmlModels.framework/Resources/QtQmlModels.prl \
		../../../N/Qt/6.8.1/macos/lib/QtQmlWorkerScript.framework/Resources/QtQmlWorkerScript.prl \
		../../../N/Qt/6.8.1/macos/lib/QtQml.framework/Resources/QtQml.prl \
		../../../N/Qt/6.8.1/macos/lib/QtNetwork.framework/Resources/QtNetwork.prl \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile project.pro
../../Qt/6.8.1/macos/mkspecs/features/spec_pre.prf:
../../Qt/6.8.1/macos/mkspecs/features/device_config.prf:
../../Qt/6.8.1/macos/mkspecs/common/unix.conf:
../../Qt/6.8.1/macos/mkspecs/common/mac.conf:
../../Qt/6.8.1/macos/mkspecs/common/macx.conf:
../../Qt/6.8.1/macos/mkspecs/common/sanitize.conf:
../../Qt/6.8.1/macos/mkspecs/common/gcc-base.conf:
../../Qt/6.8.1/macos/mkspecs/common/gcc-base-mac.conf:
../../Qt/6.8.1/macos/mkspecs/common/clang.conf:
../../Qt/6.8.1/macos/mkspecs/common/clang-mac.conf:
../../Qt/6.8.1/macos/mkspecs/qconfig.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_ext_freetype.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_ext_libjpeg.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_ext_libpng.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_ext_openxr_loader.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_charts.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_chartsqml.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_chartsqml_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_core.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_designer.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_example_icons_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_freetype_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_gui.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_help.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsplatform.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsplatform_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labssettings.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_linguist.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_network.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_png_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qml.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlcompiler.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlls_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlmeta.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlnetwork.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3d.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3d_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3deffects.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dparticles.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dutils.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dxr.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick3dxr_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktimeline.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickvectorimage.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_shadertools.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_shadertools_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_spatialaudio.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_sql.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_svg.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_tools_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_xml.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
../../Qt/6.8.1/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
../../Qt/6.8.1/macos/mkspecs/features/qt_functions.prf:
../../Qt/6.8.1/macos/mkspecs/features/qt_config.prf:
../../Qt/6.8.1/macos/mkspecs/macx-clang/qmake.conf:
../../Qt/6.8.1/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/6.8.1/macos/mkspecs/features/exclusive_builds.prf:
../../Qt/6.8.1/macos/mkspecs/features/mac/sdk.prf:
../../Qt/6.8.1/macos/mkspecs/features/toolchain.prf:
../../Qt/6.8.1/macos/mkspecs/features/mac/toolchain.prf:
../../Qt/6.8.1/macos/mkspecs/features/default_pre.prf:
../../Qt/6.8.1/macos/mkspecs/features/mac/default_pre.prf:
../../Qt/6.8.1/macos/mkspecs/features/resolve_config.prf:
../../Qt/6.8.1/macos/mkspecs/features/default_post.prf:
../../Qt/6.8.1/macos/mkspecs/features/mac/default_post.prf:
../../Qt/6.8.1/macos/mkspecs/features/mac/objective_c.prf:
../../Qt/6.8.1/macos/mkspecs/features/mac/mac.prf:
../../Qt/6.8.1/macos/mkspecs/features/warn_on.prf:
../../Qt/6.8.1/macos/mkspecs/features/permissions.prf:
../../Qt/6.8.1/macos/mkspecs/features/qt.prf:
../../Qt/6.8.1/macos/mkspecs/features/resources_functions.prf:
../../Qt/6.8.1/macos/mkspecs/features/resources.prf:
../../Qt/6.8.1/macos/mkspecs/features/moc.prf:
../../Qt/6.8.1/macos/mkspecs/features/unix/opengl.prf:
../../Qt/6.8.1/macos/mkspecs/features/unix/thread.prf:
../../Qt/6.8.1/macos/mkspecs/features/qmake_use.prf:
../../Qt/6.8.1/macos/mkspecs/features/file_copies.prf:
../../Qt/6.8.1/macos/mkspecs/features/mac/rez.prf:
../../Qt/6.8.1/macos/mkspecs/features/mac/asset_catalogs.prf:
../../Qt/6.8.1/macos/mkspecs/features/testcase_targets.prf:
../../Qt/6.8.1/macos/mkspecs/features/exceptions.prf:
../../Qt/6.8.1/macos/mkspecs/features/yacc.prf:
../../Qt/6.8.1/macos/mkspecs/features/lex.prf:
project.pro:
src/resources/resources.qrc:
../../../N/Qt/6.8.1/macos/lib/QtQuick.framework/Resources/QtQuick.prl:
../../../N/Qt/6.8.1/macos/lib/QtOpenGL.framework/Resources/QtOpenGL.prl:
../../../N/Qt/6.8.1/macos/lib/QtMultimedia.framework/Resources/QtMultimedia.prl:
../../../N/Qt/6.8.1/macos/lib/QtGui.framework/Resources/QtGui.prl:
../../../N/Qt/6.8.1/macos/lib/QtQmlMeta.framework/Resources/QtQmlMeta.prl:
../../../N/Qt/6.8.1/macos/lib/QtQmlModels.framework/Resources/QtQmlModels.prl:
../../../N/Qt/6.8.1/macos/lib/QtQmlWorkerScript.framework/Resources/QtQmlWorkerScript.prl:
../../../N/Qt/6.8.1/macos/lib/QtQml.framework/Resources/QtQml.prl:
../../../N/Qt/6.8.1/macos/lib/QtNetwork.framework/Resources/QtNetwork.prl:
../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile project.pro

qmake_all: FORCE


all: Makefile mahjong

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/resources/resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents src/tile.hpp src/tilemodel.hpp src/board.hpp $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: src/resources/resources.qrc \
		../../Qt/6.8.1/macos/libexec/rcc
	/Users/n/Qt/6.8.1/macos/libexec/rcc -name resources --no-zstd src/resources/resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_tile.cpp moc_tilemodel.cpp moc_board.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_tile.cpp moc_tilemodel.cpp moc_board.cpp
moc_tile.cpp: src/tile.hpp \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/QObject \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/QString \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/6.8.1/macos/libexec/moc
	/Users/n/Qt/6.8.1/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=14 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/n/Qt/6.8.1/macos/mkspecs/macx-clang -I/Users/n/Desktop/Strategy-9 -I/Users/N/Qt/6.8.1/macos/lib/QtQuick.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtOpenGL.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtMultimedia.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtGui.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtQmlMeta.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtQmlModels.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtQmlWorkerScript.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtQml.framework/Headers -I/Users/N/Qt/6.8.1/macos/include -I/Users/N/Qt/6.8.1/macos/include/QtQmlIntegration -I/Users/N/Qt/6.8.1/macos/lib/QtNetwork.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/N/Qt/6.8.1/macos/lib src/tile.hpp -o moc_tile.cpp

moc_tilemodel.cpp: src/tilemodel.hpp \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/QAbstractListModel \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/QVector \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/qvector.h \
		src/tile.hpp \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/QObject \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/QString \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/6.8.1/macos/libexec/moc
	/Users/n/Qt/6.8.1/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=14 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/n/Qt/6.8.1/macos/mkspecs/macx-clang -I/Users/n/Desktop/Strategy-9 -I/Users/N/Qt/6.8.1/macos/lib/QtQuick.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtOpenGL.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtMultimedia.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtGui.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtQmlMeta.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtQmlModels.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtQmlWorkerScript.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtQml.framework/Headers -I/Users/N/Qt/6.8.1/macos/include -I/Users/N/Qt/6.8.1/macos/include/QtQmlIntegration -I/Users/N/Qt/6.8.1/macos/lib/QtNetwork.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/N/Qt/6.8.1/macos/lib src/tilemodel.hpp -o moc_tilemodel.cpp

moc_board.cpp: src/board.hpp \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/QObject \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../N/Qt/6.8.1/macos/lib/QtMultimedia.framework/Headers/QSoundEffect \
		../../../N/Qt/6.8.1/macos/lib/QtMultimedia.framework/Headers/qsoundeffect.h \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/QVector \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/qvector.h \
		src/tilemodel.hpp \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/QAbstractListModel \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		src/tile.hpp \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/QString \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/6.8.1/macos/libexec/moc
	/Users/n/Qt/6.8.1/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=14 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/n/Qt/6.8.1/macos/mkspecs/macx-clang -I/Users/n/Desktop/Strategy-9 -I/Users/N/Qt/6.8.1/macos/lib/QtQuick.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtOpenGL.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtMultimedia.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtGui.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtQmlMeta.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtQmlModels.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtQmlWorkerScript.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtQml.framework/Headers -I/Users/N/Qt/6.8.1/macos/include -I/Users/N/Qt/6.8.1/macos/include/QtQmlIntegration -I/Users/N/Qt/6.8.1/macos/lib/QtNetwork.framework/Headers -I/Users/N/Qt/6.8.1/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/N/Qt/6.8.1/macos/lib src/board.hpp -o moc_board.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp ../../../N/Qt/6.8.1/macos/lib/QtGui.framework/Headers/QGuiApplication \
		../../../N/Qt/6.8.1/macos/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../N/Qt/6.8.1/macos/lib/QtQml.framework/Headers/QQmlApplicationEngine \
		../../../N/Qt/6.8.1/macos/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		../../../N/Qt/6.8.1/macos/lib/QtQml.framework/Headers/QQmlContext \
		../../../N/Qt/6.8.1/macos/lib/QtQml.framework/Headers/qqmlcontext.h \
		src/board.hpp \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/QObject \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../N/Qt/6.8.1/macos/lib/QtMultimedia.framework/Headers/QSoundEffect \
		../../../N/Qt/6.8.1/macos/lib/QtMultimedia.framework/Headers/qsoundeffect.h \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/QVector \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/qvector.h \
		src/tilemodel.hpp \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/QAbstractListModel \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		src/tile.hpp \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/QString \
		../../../N/Qt/6.8.1/macos/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_tile.o: moc_tile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tile.o moc_tile.cpp

moc_tilemodel.o: moc_tilemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tilemodel.o moc_tilemodel.cpp

moc_board.o: moc_board.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_board.o moc_board.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

